# yamllint --format github .github/workflows/create_release.yml
---
name: create_release

# We create a release version on a trigger tag, regardless of if the commit is documentation-only.
#
# See https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
on:
  push:
    tags: 'release-[0-9]+.[0-9]+.[0-9]+**'  # Ex. release-1.2.3

jobs:
  create_release:
    runs-on: ubuntu-20.04  # newest available distribution, aka focal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create Release
        run: |  # GITHUB_REF will be refs/tags/release-MAJOR.MINOR.PATCH
#          build-bin/git/login_git &&
          build-bin/maven/maven_release $(echo ${GITHUB_REF} | cut -d/ -f 3)
